//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products_Categories.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UserAccountId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string User_FirstName { get; set; }
        public string User_LastName { get; set; }
    }
}
